data = [
    {
        "name": "Amir Tataloo",
        "from": "Iran",
        "follower": 12000000,
        "job": "Rapper/Singer",
    },
    {"name": "Yas", "from": "Iran", "follower": 8500000, "job": "Rapper"},
    {"name": "Reza Pishro", "from": "Iran", "follower": 6500000, "job": "Rapper"},
    {"name": "Zedbazi", "from": "Iran", "follower": 10000000, "job": "Hip-Hop Group"},
    {"name": "Sijal", "from": "Iran", "follower": 5200000, "job": "Rapper"},
    {"name": "Leito", "from": "Iran", "follower": 5000000, "job": "Rapper"},
    {"name": "Khalse", "from": "Iran", "follower": 4800000, "job": "Rapper"},
    {"name": "Bahram", "from": "Iran", "follower": 4500000, "job": "Rapper"},
    {"name": "Sorena", "from": "Iran", "follower": 4300000, "job": "Rapper"},
    {"name": "Hichkas", "from": "Iran", "follower": 6000000, "job": "Rapper"},
    {"name": "Shayea", "from": "Iran", "follower": 5500000, "job": "Rapper"},
    {"name": "Ali Owj", "from": "Iran", "follower": 2200000, "job": "Rapper"},
    {"name": "Ho3ein", "from": "Iran", "follower": 7000000, "job": "Rapper"},
    {"name": "Mokhales", "from": "Iran", "follower": 1800000, "job": "Rapper"},
    {"name": "Sami Beigi", "from": "Iran", "follower": 5800000, "job": "Singer/Rapper"},
    {"name": "Erfan", "from": "Iran", "follower": 4000000, "job": "Rapper"},
    {"name": "Arash AP", "from": "Iran", "follower": 3500000, "job": "Singer/Rapper"},
    {"name": "Tohi", "from": "Iran", "follower": 4600000, "job": "Rapper"},
    {"name": "Ali Quf", "from": "Iran", "follower": 2000000, "job": "Rapper"},
    {"name": "Koorosh", "from": "Iran", "follower": 5400000, "job": "Rapper"},
    {"name": "Sami Low", "from": "Iran", "follower": 1700000, "job": "Rapper"},
    {"name": "Putak", "from": "Iran", "follower": 3900000, "job": "Rapper"},
    {"name": "021Kid", "from": "Iran", "follower": 3600000, "job": "Rapper"},
    {"name": "Sepehr Khalse", "from": "Iran", "follower": 4800000, "job": "Rapper"},
    {"name": "Vinak", "from": "Iran", "follower": 1600000, "job": "Rapper"},
    {"name": "Arta", "from": "Iran", "follower": 4200000, "job": "Rapper"},
    {"name": "Canis", "from": "Iran", "follower": 1500000, "job": "Rapper"},
    {"name": "Ali Sorena", "from": "Iran", "follower": 4300000, "job": "Rapper"},
    {
        "name": "Mehrad Hidden",
        "from": "Iran",
        "follower": 6100000,
        "job": "Rapper/Producer",
    },
    {"name": "Sina Sae", "from": "Iran", "follower": 3400000, "job": "Rapper"},
]
